spring:
  batch:
    job:
      names: ${job.name:NONE}
#  datasource:
#    url: jdbc:mysql://localhost:3306/springbatch?characterEncoding=UTF-8&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      username: root
#      password: password
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
