spring:
  datasource:
    hikari:
      username: root
      password: password
      jdbc-url: jdbc:mysql://localhost:3306/springbatch?characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    initialize-schema: never