spring:
  batch:
    job:
      names: ${job.name:NONE}
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
